spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuiguopengs/SpringCloudConfig/
          search-paths: respo
      label: master
server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/


